[package]
name = "input"
version = "0.1.0"
authors = ["jdtw"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
