[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
input = { path = "../input" }
pest = "2.7.1"
pest_derive = "2.7.1"
util = { path = "../util" }
